name: Finalize Rankings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"  # 22:00 JST

jobs:
  finalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -e .

      - name: Finalize rankings
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          TODAY_JST=$(TZ=Asia/Tokyo date '+%Y-%m-%d')
          python scripts/finalize_rankings.py --date $TODAY_JST
